services:
  admin1:
    build:
      context: admin
      dockerfile: ../Dockerfile
    hostname: admin1
    container_name: admin1
    command: >
      --cluster-a-seeds "localhost:9092,localhost:9092,localhost:9094"
      --cluster-b-seeds "localhost:9095,localhost:9096,localhost:9097"
      --topic "cron-topic"
      --partitions 3
      --replication-factor 3
    network_mode: host

  producer1:
    build:
      context: producer
      dockerfile: ../Dockerfile
    hostname: producer1
    container_name: producer1
    volumes:
      - ./producer/customcrontab:/app/customcrontab
    command: >
      --path "customcrontab"
      --cluster-a-seeds "localhost:9092,localhost:9092,localhost:9094"
      --cluster-b-seeds "localhost:9095,localhost:9096,localhost:9097"
      --topic "cron-topic"
    depends_on:
      - admin1
    network_mode: host

  consumer1:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer1
    container_name: consumer1
    command: >
      --seeds "localhost:9092,localhost:9092,localhost:9094"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host
  
  consumer2:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer2
    container_name: consumer2
    command: >
      --seeds "localhost:9092,localhost:9092,localhost:9094"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host

  consumer3:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer3
    container_name: consumer3
    command: >
      --seeds "localhost:9092,localhost:9092,localhost:9094"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host

  consumer4:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer4
    container_name: consumer4
    command: >
      --seeds "localhost:9095,localhost:9096,localhost:9097"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host

  consumer5:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer5
    container_name: consumer5
    command: >
      --seeds "localhost:9095,localhost:9096,localhost:9097"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host

  consumer6:
    build:
      context: consumer
      dockerfile: ../Dockerfile    
    hostname: consumer6
    container_name: consumer6
    command: >
      --seeds "localhost:9095,localhost:9096,localhost:9097"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host