services:
  admin1:
    build:
      context: admin
      dockerfile: ../Dockerfile
    hostname: admin1
    container_name: admin1
    command: >
      --seeds "localhost:9092"
      --topic "cron-topic"
      --partitions 2
      --replication-factor 1
    network_mode: host

  producer1:
    build:
      context: producer
      dockerfile: ../Dockerfile
    hostname: producer1
    container_name: producer1
    volumes:
      - ./producer/customcrontab:/app/customcrontab
    command: >
      --path "customcrontab"
      --seeds "localhost:9092"
      --topic "cron-topic"
    depends_on:
      - admin1
    network_mode: host

  consumer1:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer1
    container_name: consumer1
    command: >
      --seeds "localhost:9092"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host
  
  consumer2:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer2
    container_name: consumer2
    command: >
      --seeds "localhost:9092"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host

  consumer3:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer3
    container_name: consumer3
    command: >
      --seeds "localhost:9092"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host

  consumer4:
    build:
      context: consumer
      dockerfile: ../Dockerfile
    hostname: consumer4
    container_name: consumer4
    command: >
      --seeds "localhost:9092"
      --topic "cron-topic"
    depends_on:
      - admin1
      - producer1
    network_mode: host