{
 "title": "Kafka Cron Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Cron Jobs Scheduled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cron_jobs_scheduled_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cron Job Schedule Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_job_schedule_failures_total{job=\"producer1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Produced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cron_jobs_produced_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cron Job Produce Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_producing_failures_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Consumed Cluster A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_consumed_total{job=\"consumer-cluster-a\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Execution Time Cluster A",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, topic, cron_job_id, cron_job_command) (rate(cron_job_execution_time_seconds_bucket{topic=\"cluster-a\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Executed Cluster A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_executed_total{job=\"consumer-cluster-a\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Consumed Cluster B",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_consumed_total{job=\"consumer-cluster-b\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Execution Time Cluster B",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cron_job_command, cron_job_id, topic) (rate(cron_job_execution_time_seconds_bucket{topic=\"cluster-b\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Executed Cluster B",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_executed_total{job=\"consumer-cluster-a\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}