FROM golang:1.22

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o api-server ./cmd/api-server

EXPOSE 8081

ENTRYPOINT ["/app/api-server"]

CMD ["--port", "8081"]