FROM golang:1.22

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o static-server ./cmd/static-server

EXPOSE 8082

ENTRYPOINT ["/app/static-server"]

CMD ["--path", "/app/assets", "--port", "8082"]