FROM nginx:latest

COPY config/nginx.conf /etc/nginx/nginx.conf
COPY config/mime.types /etc/nginx/mime.types

EXPOSE 8080

# TODO: remove this dockerfile completely and use nginx:latest and figure out how to copy the .conf and mime.types