services:
  raft:
    build: .
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}   
  client:
    build:
      dockerfile: ./Dockerfile.client
    deploy:
      mode: replicated
      replicas: 1