{
 "title": "Kafka Cron Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cron Job Scheduling & Producing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Cron Job Schedule Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_job_schedule_failures_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Scheduled Successfully",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cron_jobs_scheduled_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cron Jobs Produced Successfully",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cron_jobs_produced_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cron Job Produce Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_producing_failures_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Consumed - Cluster A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_consumed_total{job=\"consumer-cluster-a\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Consumed - Cluster B",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_consumed_total{job=\"consumer-cluster-b\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cron Job Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Cron Jobs Executed - Cluster A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_executed_total{job=\"consumer-cluster-a\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Failed Execution - Cluster A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_execution_failed_total{job=\"consumer-cluster-a\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Executed - Cluster B",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_executed_total{job=\"consumer-cluster-b\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Failed Execution - Cluster B",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_execution_failed_total{job=\"consumer-cluster-b\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Retries Total - Cluster A Retry",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_retried_total{job=\"consumer-cluster-a-retry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Retry Total Failure - Cluster B Retry",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_retry_failed_total{job=\"consumer-cluster-b-retry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Jobs Retries Total - Cluster B Retry",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_retried_total{job=\"consumer-cluster-b-retry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Retries Total Failure - Cluster A",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cron_jobs_retry_failed_total{job=\"consumer-cluster-a-retry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Execution Duration 95th Percentile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Cron Job Execution Duration (0.95) - Cluster A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, topic) (rate(cron_job_execution_time_seconds_bucket{topic=\"cluster-a\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Execution Duration (0.95) - Cluster B",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, topic) (rate(cron_job_execution_time_seconds_bucket{topic=\"cluster-b\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Schedule to Execute Start / Complete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Cron Job Scheduled to Execute Delay (0.95) - Cluster A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, topic) (cron_job_execution_delay_start_seconds_bucket{topic=\"cluster-a\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Scheduled to Completed Duration (0.95) - Cluster B",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, topic) (cron_job_execution_delay_end_seconds_bucket{topic=\"cluster-a\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Scheduled to Execute Delay (0.95) - Cluster B",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, topic) (cron_job_execution_delay_start_seconds_bucket{topic=\"cluster-b\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Scheduled to Complete Duration (0.95) - Cluster B",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, topic) (cron_job_execution_delay_end_seconds_bucket{topic=\"cluster-b\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}