name: batch-processing tests
on: [push]
defaults:
  run:
    working-directory: projects/batch-processing
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "projects/batch-processing/go.mod"
          cache: false
      - name: Test
        run: make test
